### ISSUE TITLE
С тысячами не работает.

### ISSUE THREAD

**Issue by slui861** [GlebBatykov/numbers_to_words_russian#1]
621 824 например. 
Выведет "Шестьсот двадцать один тысяч" =)

**Comment by slui861** [comment]
Аналогичная проблема с миллионами.
В общем тут надо польностью переделывать.

**Comment by GlebBatykov** [comment]
Тестирую код

final number = 621824;

print(NumbersToWordsRussian.convert(number));

И получаю: шестьсот двадцать один тысяч восемьсот двадцать четыре

Если ты имеешь ввиду склонение, то для тех задач где я использовал этот конвертер - было достаточно и того что есть

**Comment by slui861** [comment]
Должно быть "шестьсот двадцать ОДНА тысячА восемьсот двадцать четыре". 
И с миллионами не работает, и с числами одна, две тысяЧИ и так далее. Код не рабочий, фактически. 
Я локально у себя всё переделал, но выкладывать не рабочее решение на flutter.pub тоже не стоит.

**Comment by GlebBatykov** [comment]
Если в твоем кейсе подобное отсутствие склонений не подошло, и ты исправил эту проблему - почему бы тебе не выложить свое решение на pub, или не предложить эти исправления в PR-е?
